import { z } from 'zod';

export type AssetLifecycleStatus = 'UPLOADED'|'PROCESSING'|'INSPECTED'|'REVIEW_REQUIRED'|'CALIBRATED'|'APPROVED'|'PUBLISHED'|'PROCESSING_FAILED'|'MANUAL_REVIEW_REQUIRED';
export type TempleProcessingMode = 'auto'|'full'|'shortened'|'disabled';
export type CoordinateAxis = '+X'|'-X'|'+Y'|'-Y'|'+Z'|'-Z';
export interface Vector3D { x:number; y:number; z:number; }
export interface Box3D { min:Vector3D; max:Vector3D; size:Vector3D; center:Vector3D; }
export interface ManualVTOTransform { position: Vector3D; rotation: Vector3D; scale: number; }
export interface SceneNodeSummary { name:string; type:string; isMesh:boolean; vertexCount?:number; faceCount?:number; materialNames?:string[]; children?:SceneNodeSummary[]; }
export interface SpatialZSlice { sliceIndex:number; zRange:[number,number]; vertexCount:number; xSpan:[number,number]; ySpan:[number,number]; label:'Rear Temples'|'Mid Temples'|'Front Hinges'|'Front Frame / Lenses'; }
export interface DetectedFeatureRegions { bridge:{center:Vector3D;innerContactZ:number;frontZ:number;confidence:number}; hinges:{left:Vector3D;right:Vector3D;confidence:number}; temples:{leftExtent:[number,number];rightExtent:[number,number];hasSevereRearOverhang:boolean;recommendedCutoffRatio?:number;confidence:number}; frontFrame:{zSpan:[number,number];thickness:number}; }
export interface AssetInspectionReport { assetId:string;fileName:string;fileSizeBytes:number;meshCount:number;totalVertices:number;totalFaces:number;materialNames:string[];textureCount:number;hasBonesOrSkin:boolean;hasMorphTargets:boolean;nativeBounds:Box3D;inferredOrientation:{forward:CoordinateAxis;up:CoordinateAxis;lateral:CoordinateAxis;confidence:number};detectedFeatures:DetectedFeatureRegions;sceneHierarchy:SceneNodeSummary;zSlices:SpatialZSlice[];inspectedAt:string; }
export interface ValidationCheckResult { category:'Geometry'|'Materials'|'Textures'|'Dimensions'|'Transforms';name:string;status:'PASS'|'WARNING'|'FAIL';message:string;details?:Record<string,unknown>; }
export interface AssetValidationReport { assetId:string;overallStatus:'PASS'|'REVIEW_REQUIRED'|'FAIL';checks:ValidationCheckResult[];summary:{passes:number;warnings:number;failures:number};validatedAt:string; }
export const OpticalDimensionsSchema=z.object({frameWidthMm:z.number().positive().nullable(),lensWidthMm:z.number().positive().nullable(),bridgeWidthMm:z.number().positive().nullable(),templeLengthMm:z.number().positive().nullable()});
export const TempleProcessingProfileSchema=z.object({mode:z.enum(['auto','full','shortened','disabled']).default('auto'),strategy:z.string().default('preserve-visible-temple'),cutRatio:z.number().min(.2).max(1).default(.7),customCutZ:z.number().optional(),preserveFrontRims:z.boolean().default(true),preserveHinges:z.boolean().default(true),useMaterialClipping:z.boolean().default(false)});
export const BridgeRegistrationSchema=z.object({x:z.number().nullable(),y:z.number().nullable(),z:z.number().nullable()});
export const ManualVTOTransformSchema=z.object({position:z.object({x:z.number(),y:z.number(),z:z.number()}),rotation:z.object({x:z.number(),y:z.number(),z:z.number()}),scale:z.number().positive()});
export const AssetCalibrationMetadataSchema=z.object({assetId:z.string(),name:z.string(),status:z.enum(['UPLOADED','PROCESSING','INSPECTED','REVIEW_REQUIRED','CALIBRATED','APPROVED','PUBLISHED','PROCESSING_FAILED','MANUAL_REVIEW_REQUIRED']).default('INSPECTED'),physicalDimensions:OpticalDimensionsSchema,registration:z.object({bridge:BridgeRegistrationSchema,measuredNativeWidth:z.number().positive(),widthMultiplier:z.number().positive().default(1),rotationOffsetEuler:z.object({x:z.number().default(0),y:z.number().default(0),z:z.number().default(0)}).default({x:0,y:0,z:0}),pantoscopicTilt:z.number().default(-12)}),manualTransform:ManualVTOTransformSchema.default({position:{x:0,y:0,z:0},rotation:{x:0,y:0,z:0},scale:1}),orientation:z.object({forward:z.string().default('+Z'),up:z.string().default('+Y'),handedness:z.enum(['right-handed','left-handed']).default('right-handed')}).default({forward:'+Z',up:'+Y',handedness:'right-handed'}),templeProcessing:TempleProcessingProfileSchema,versioning:z.object({processorVersion:z.string().default('manual'),sourceVersion:z.number().int().positive().default(1),vtoVersion:z.number().int().positive().default(1),calibrationVersion:z.number().int().positive().default(1)}).default({processorVersion:'manual',sourceVersion:1,vtoVersion:1,calibrationVersion:1}),paths:z.object({sourceGlbUrl:z.string(),vtoGlbUrl:z.string(),previewImages:z.array(z.string()).default([])}),metadataSource:z.string().default('McDaves VTO Manual Calibration Studio'),updatedAt:z.string()});
export type OpticalDimensions=z.infer<typeof OpticalDimensionsSchema>;
export type TempleProcessingProfile=z.infer<typeof TempleProcessingProfileSchema>;
export type BridgeRegistration=z.infer<typeof BridgeRegistrationSchema>;
export type AssetCalibrationMetadata=z.infer<typeof AssetCalibrationMetadataSchema>;
