'use client';
import { useEffect, useState } from 'react';
import { globalVTOAssetRegistry } from '@/vto-pipeline/registry/VTOAssetRegistry';
import type { AssetCalibrationMetadata } from '@/vto-pipeline/types/AssetTypes';
const DEFAULT_ORIENTATION={forward:'+Z',up:'+Y',handedness:'right-handed'} as const;
const DEFAULT_TEMPLE_PROCESSING={mode:'disabled',strategy:'manual',cutRatio:1,preserveFrontRims:true,preserveHinges:true,useMaterialClipping:false} as const;
let fetchPromise:Promise<void>|null=null; let isFetched=false;
export function useVTOAssets(){
 const [loading,setLoading]=useState(!isFetched); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{ if(isFetched){setLoading(false);return;} if(!fetchPromise){fetchPromise=(async()=>{try{const res=await fetch('/api/vto/assets');if(!res.ok)throw new Error('Failed to fetch VTO assets');const rows=await res.json();if(Array.isArray(rows))rows.forEach((row:any)=>{const manual=row.manual_transform??{position:{x:0,y:0,z:0},rotation:{x:0,y:0,z:0},scale:1};const metadata:AssetCalibrationMetadata={assetId:row.asset_id,name:row.name,status:row.status,physicalDimensions:{frameWidthMm:row.frame_width_mm!=null?Number(row.frame_width_mm):null,lensWidthMm:row.lens_width_mm!=null?Number(row.lens_width_mm):null,bridgeWidthMm:row.bridge_width_mm!=null?Number(row.bridge_width_mm):null,templeLengthMm:row.temple_length_mm!=null?Number(row.temple_length_mm):null},registration:{bridge:{x:row.bridge_x!=null?Number(row.bridge_x):0,y:row.bridge_y!=null?Number(row.bridge_y):0,z:row.bridge_z!=null?Number(row.bridge_z):0},measuredNativeWidth:Number(row.measured_native_width)||1,widthMultiplier:Number(row.width_multiplier)||1,rotationOffsetEuler:row.rotation_offset_euler||{x:0,y:0,z:0}},manualTransform:manual,orientation:DEFAULT_ORIENTATION,templeProcessing:DEFAULT_TEMPLE_PROCESSING,versioning:{processorVersion:'manual',sourceVersion:1,vtoVersion:1,calibrationVersion:Number(row.calibration_version)||1},paths:{sourceGlbUrl:row.source_glb_url||'',vtoGlbUrl:row.vto_glb_url||row.source_glb_url||'',previewImages:row.preview_images||[]},metadataSource:row.metadata_source||'DB',updatedAt:row.updated_at};globalVTOAssetRegistry.registerAsset(metadata);});isFetched=true;}catch(err:any){setError(err.message);}finally{setLoading(false);}})();}else fetchPromise.then(()=>setLoading(false));},[]);return {loading,error};}
